[project]
name = "inferencer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnxruntime-gpu[cuda, cudnn]>=1.23.2",
    "opencv-python>=4.13.0.90",
    "tqdm>=4.67.1",
]
